### ISSUE TITLE
https://project--owl.slack.com no longer active

### ISSUE THREAD

**Issue by FredWagen** [Project-Owl/dms-lite#13]
Probably not the right space to leave this issue ... but what replaced your "no longer active" https://project--owl.slack.com?
I would like to motivate at least one of my student to try this superb project idea.
Best regards
Fred
https://people.hes-so.ch/en/profile/jeanfred.wagen

**Comment by knouse1344** [comment]
thank you for the note, @FredWagen !  We are solving this right now...

**Comment by TimoWielink** [comment]
@FredWagen that sounds great, feel free to join the slack and reach out to us! If you want more information the Wiki of this repository can help you [Clusterduck Protocol](https://github.com/Code-and-Response/ClusterDuck-Protocol )
