### ISSUE TITLE
Can you post some screenshots in readme?

### ISSUE THREAD

**Issue by hexclann** [Project-Owl/dms-lite#19]
Is this similar to the dashboard shown in Linus Tech Tips video?

**Comment by TimoWielink** [comment]
@hexclann 

Hi there, It is not actually.

The dashboard from the Linus tech Tips video is built into the DMS Cloud version. The DMS lite delivers some of the functionality but is made for the OS Community. If you want more info on both feel free to join our slack. [project-owl.com/slack](project-owl.com/slack).
 
 I will add some screenshots!
 
 Timo

**Comment by hexclann** [comment]
Thanks for the info @TimoWielink !
