### ISSUE TITLE
serial_sqlwriter.py never creates the clusterData table even when it does not exist

### ISSUE THREAD

**Issue by Teikahym** [Project-Owl/dms-lite#21]
**Issue:** The try-block executing the "CREATE TABLE IF NOT EXISTS" query is unreachable. 

**Potential Solution:** Move the try-block above the while-loop.

**Comment by nfeuer** [comment]
Thank you for pointing that out! We will check this out during our stream

**Comment by Teikahym** [comment]
resolved with: https://github.com/Project-Owl/dms-lite/pull/23
