### ISSUE TITLE
Issues in Wifi-install.sh

### ISSUE THREAD

**Issue by r41d** [Project-Owl/dms-lite#26]
I noticed some quirks in `Wifi-install.sh` which are as follows:
- `sqlite3` is contained in the Python 3 standard library and doesn't need to be installed, PyPi has no package with that name, hence the `pip3 install sqlite3` line should be removed
- doubles dashes for curl paramters in the last line are wrong, it needs to be one dash
- the `-y` parameter for bash on Raspbian yields this error: `bash: -y: invalid option`, hence it should be removed from the script
- nodejs 10 installer gives big deprecation warnings, maybe update to 12 ? (I'm no expert on that matter)

**Comment by nfeuer** [comment]
Hi @r41d! Thanks for pointing those out. We will test your suggestions and push an update. We will also check if this affects our docker version https://github.com/Project-Owl/dms-lite-docker

**Comment by Evilgeniusnerd** [comment]
@r41d  So I just pushed an update to correct the script per your recommendations. Thank you for finding the bugs and pointing them out.  As Nick mentioned we have recently built DMS-Lite into docker to avoid a lot of these dependencies issues and making it super easy to use.  You will still see some NodeJS depreciation issues but that is due to binary not being updated for the Pi hardware.

**Comment by nfeuer** [comment]
Also @r41d hit us up in our Slack https://www.project-owl.com/slack. Would be interested to learn more about your project and how we might be able to help!

**Comment by r41d** [comment]
I actually learned about dms-lite-docker shortly after I created this issue.
I think the Readme of this project should have a hint that can direct people to dms-lite-docker, regardless whether this project will be deprecated or properly maintained.

**Comment by r41d** [comment]
Where did you push those changes @Evilgeniusnerd 
I don't see them anywhere :thinking:

**Comment by r41d** [comment]
My bad, I just looked at the last line with the (still erroneous) curl paramter, will open PR momentarily

**Comment by Evilgeniusnerd** [comment]
Changes are here @r41d  https://github.com/Project-Owl/dms-lite/blob/master/Wifi-install.sh.  Also as mentioned the focus has been a move to DMS- Lite Docker which you can find here: https://github.com/Project-Owl/dms-lite-docker
