### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by mrieder99** [Project-Owl/dms-lite#7]
The use of docker containers would simplify the deployment of the software and other operating systems (e.g. Ubuntu Linux, Hypriot OS, Balena OS) could be supported. Furthermore, dependencies can be better managed and the installation can be done via script.

Here is a link to an example that shows how a Node.js application can be dockerized: https://nodejs.org/fr/docs/guides/nodejs-docker-webapp/

**Comment by hawk4031** [comment]
@krook also suggested we have a look at [Open Horizon](https://www.lfedge.org/projects/openhorizon/) as a way to manage containerization at the edge.

**Comment by Evilgeniusnerd** [comment]
@mrieder99  Just wanted to give you an update. We are currently working on the Dockerization of DMS-Lite. We should be publishing this either this week or next upcoming week.  Just trying to knock out a few more bugs. Let me know if you are still interested the more eyes and testing on it the better.

**Comment by nfeuer** [comment]
Docker version is live! https://github.com/Project-Owl/dms-lite-docker

**Comment by krook** [comment]
Excellent!
